swagger: '2.0'
info:
  description: This is for watching our your important people.
  version: 1.0.0
  title: Watching
  contact:
    email: kyuuki.japan@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: rails-dev.akoba.xyz
basePath: /v1
tags:
  - name: users
    description: Operations about user
schemes:
  - https
  - http
paths:
  /user:
    post:
      tags:
        - users
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            type: object
            properties:
              phoneNumber:
                type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              id:
                type: integer
              key:
                type: string
externalDocs:
  description: Find out more about Watching
  url: 'https://watching-project.herokuapp.com/'
