swagger: '2.0'
info:
  description: This is for watching our your important people.
  version: 1.0.0
  title: Watching
  contact:
    email: kyuuki.japan@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: rails-dev.akoba.xyz
basePath: /v1
tags:
  - name: users
    description: Operations about user
  - name: events
    description: Operations about event
schemes:
  - https
  - http
# https://swagger.io/docs/specification/2-0/authentication/api-keys/
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: x-api-key
paths:
  /user:
    post:
      tags:
        - users
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            properties:
              id:
                type: integer
              api_key:
                type: string
    put:
      tags:
        - users
      summary: Update user
      security:
        - APIKeyHeader: []
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              nick_name:
                type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: object
  /events:
    get:
      tags:
        - events
      summary: Update user
      security:
        - APIKeyHeader: []
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              properties:
                user_id:
                  type: integer
                description: 
                  type: string

externalDocs:
  description: Find out more about Watching
  url: 'https://watching-project.herokuapp.com/'
